### ISSUE TITLE
[Bug]: Otter VsCode application crash on start

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#2580]
### Application name

VsCode Extension

### Version

11.4.0

### Reproduction steps

install [amadeusitgroup.otter-devtools](https://marketplace.visualstudio.com/items?itemName=AmadeusITGroup.otter-devtools) application on Visual Studio Code.

### Current result

```
Require stack:
- /Users/kpanot/.vscode/extensions/amadeusitgroup.otter-devtools-11.4.0/src/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Function.n._resolveFilename (node:electron/js2c/utility_init:2:16068)
    at Function.t._resolveFilename (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:167:22816)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at /Users/kpanot/.yarn/cache/eslint-npm-8.57.1-dd20287a5a-5504fa2487.zip/node_modules/eslint/lib/rule-tester/rule-tester.js:56:20
    at /Users/kpanot/.vscode/extensions/amadeusitgroup.otter-devtools-11.4.0/src/extension.js:1:222
    at /Users/kpanot/.yarn/cache/eslint-npm-8.57.1-dd20287a5a-5504fa2487.zip/node_modules/eslint/lib/rule-tester/index.js:4:17
    at /Users/kpanot/.vscode/extensions/amadeusitgroup.otter-devtools-11.4.0/src/extension.js:1:222
    at /Users/kpanot/.yarn/cache/eslint-npm-8.57.1-dd20287a5a-5504fa2487.zip/node_modules/eslint/lib/api.js:15:24
    at /Users/kpanot/.vscode/extensions/amadeusitgroup.otter-devtools-11.4.0/src/extension.js:1:222
    at Object.<anonymous> (/Users/kpanot/.vscode/extensions/src/intellisense/configuration.ts:2:24)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at Function.c._load (node:electron/js2c/node_init:2:16955)
    at Function.e._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:10896)
    at Function.t._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:167:22534)
    at Function.i._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:21138)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at Module.require (/Users/kpanot/.vscode/extensions/github.copilot-chat-0.23.0/dist/extension.js:238:34657)
    at require (node:internal/modules/helpers:179:18)
    at zz.xb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:167:23854)
    at async Promise.all (index 0)
```

### Expected result

No start issue

**Comment by kpanot** [comment]
Reduce the priority as a temporary fix allow the usage of the application (with the exception of EsLint checks when `espree` is not globally provided)
